module Keywords

    KEYWORDS = {
        SELECT: 'SELECT',
        CREATE: 'CREATE',
        UPDATE: 'UPDATE',
        DELETE: 'DELETE',
        FROM: 'FROM',
        SET: 'SET',
        VALUES: 'VALUES',
        WHERE: 'WHERE',
        USE: 'USE',
        UNIQUE: 'UNIQUE',
        TO: 'TO',
        SHOW: 'SHOW',
        REPLACE: 'REPLACE',
        RENAME: 'RENAME',
        PARTITION: 'PARTITION',
        ORDER: 'ORDER',
        OR: 'OR',
        NOT: 'NOT',
        LIMIT: 'LIMIT',
        LIKE: 'LIKE',
        IS: 'IS',
        INSERT: 'INSERT',
        GROUP: 'GROUP',
        FOR: 'FOR',
        FALSE: 'FALSE',
        TRUE: 'TRUE',
        EXPLAIN: 'EXPLAIN',
        EXISTS: 'EXISTS',
        DROP: 'DROP',
        DISTINCT: 'DISTINCT',
        DESC: 'DESC',
        DATABASE: 'DATABASE',
        CONTAINS: 'CONTAINS',
        BY: 'BY',
        BETWEEN: 'BETWEEN',
        AS: 'AS',
        AND: 'AND',
        ALTER: 'ALTER',
        INTO: 'INTO',
        IN: 'IN',
        HAVING: 'HAVING',
    }
end